name = "bientot-de-retour"
main = "worker.js"
compatibility_date = "2026-06-01"
workers_dev = false
routes = [
  { pattern = "premadelab.eu/*", zone_name = "premadelab.eu" },
  { pattern = "dev.premadelab.eu/*", zone_name = "premadelab.eu" },
  { pattern = "schultz-thomas.fr/*", zone_name = "schultz-thomas.fr" },
  { pattern = "dev.schultz-thomas.fr/*", zone_name = "schultz-thomas.fr" },
]
